### ISSUE TITLE
As a user, I want to be able to create channels

### ISSUE THREAD

**Issue by gordonpn** [gpnn/slack-clone#6]
Core feature

Tasks: 
- [x] Express route (API endpoint) to add (http post) users to the database and get (http get) a user by his ID **(Mack)** #13 
- [x] Express route to add (http post) channels to the database and get (http get) a channel by ID **(Gordon)** #14 
- [x] Create Mongoose Schemas (MongoDB objects) for users and channels needed for endpoints **(Mack)** #16 
- [x] Make link between the Create Channel button in client and POST request **(Gordon)** #20
