### ISSUE TITLE
As a user, I want to be able to join channels

### ISSUE THREAD

**Issue by gordonpn** [gpnn/slack-clone#7]
Core feature
Sub-tasks:

- [x] #15 Functionality to get all the channels and display them
- [x] #17 Front End functionality to invite a user to a channel
- [x] #24 User login UI 
- [x] #25 Get channels for specific user ID
